feat: adding commit-msg hook

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -1,33 +1,21 @@
 #!/bin/sh
-# Get the user's email from Git configuration
-EMAIL=$(git config user.email)
+#!/usr/bin/env bash
+# File generated by pre-commit: https://pre-commit.com
+# ID: 138fd403232d2ddd5efb44317e38bf03
 
-validate_company_domain() {
-    if [[ $EMAIL == *"@fusemachines.com"* ]]; then
-        echo "[INFO] Verified email: $EMAIL"
-    else
-        echo "[ERROR] Invalid email domain: $EMAIL"
-        echo "[ERROR] Please configure the company email and retry."
-        echo "Steps:"
-        echo "git config user.email \"your.name@fusemachines.com\""
-        exit 1
-    fi
-}
+# start templated
+INSTALL_PYTHON='C:\Program Files\Python311\python.exe'
+ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
+# end templated
 
-# Check for trailing whitespaces
-check_trailing_whitespace() {
-    local files_with_trailing_ws=$(git diff --check --cached | grep -E "^\+.*[[:space:]]+$")
-    if [ -n "$files_with_trailing_ws" ]; then
-        echo "[ERROR] Trailing whitespaces detected in the following files:"
-        echo "$files_with_trailing_ws"
-        echo "[ERROR] Remove the trailing whitespaces before committing."
-        exit 1
-    fi
-}
+HERE="$(cd "$(dirname "$0")" && pwd)"
+ARGS+=(--hook-dir "$HERE" -- "$@")
 
-# Validate company domain
-validate_company_domain
-# Check for trailing whitespaces
-check_trailing_whitespace
-# Exit successfully
-exit 0
+if [ -x "$INSTALL_PYTHON" ]; then
+    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
+elif command -v pre-commit > /dev/null; then
+    exec pre-commit "${ARGS[@]}"
+else
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+    exit 1
+fi
